---

- name: Install Composer package dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ composer_dependencies }}"
  tags:
    - composer

- name: Check if Composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_bin
  tags:
    - composer

- include: install.yml
  when: not composer_bin.stat.exists
  tags:
    - composer

- name: Update Composer
  composer:
    command: self-update
    global_command: yes
  when: composer_use_latest
  tags:
    - composer

- name: Ensure composer directory exists
  file:
    path: "{{ composer_home_path }}"
    owner: "{{ composer_user }}"
    state: directory

- name: Add GitHub OAuth token for Composer
  template:
    src: "auth.json.j2"
    dest: "{{ composer_home_path }}/auth.json"
    owner: "{{ composer_user }}"
  when: composer_github_oauth_token != ''
  tags:
    - composer
    - github_oauth