---

- name: Install Composer package dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ composer_dependencies }}"
  tags:
    - composer

- name: Check if Composer is installed
  stat:
    path: /usr/local/bin/composer
  register: composer_bin
  tags:
    - composer

- include: install.yml
  when: not composer_bin.stat.exists
  tags:
    - composer

- name: Update Composer
  composer:
    command: self-update
    global_command: yes
  tags:
    - composer


- name: Set github oauth config
  composer:
    command: config
    arguments: '-g github-oauth.github.com "{{ github_oauth_token }}"'
    working_dir: "/home/{{ composer_user }}"
  when: github_oauth_token is defined
  tags:
    - composer
    - github_oauth
